server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.1.1.113:8761/eureka/,http://10.1.1.115:8761/eureka/
#reward
spring:
  profiles:
     active: dev
  datasource:
    reward:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tps2?useSSL=false
      username: root
      password: 123456
    order:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tps2?useSSL=false
      username: root
      password: 123456
    user:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tps2?useSSL=false
      username: root
      password: 123456
    title:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tps2?useSSL=false
      username: root
      password: 123456

logging:
  level:
    com:
      tps: debug
  org:
    springframework:
      web: debug
    transaction: debug
  mybatis: error
